application: inspired-photon-127022
version: 1
runtime: php55
api_version: 1
handlers:
- url: /
  static_files: index.html
  upload: index.html

- url: /index\.html
  static_files: index.html
  upload: index.html

- url: /(.*\.(png|jpg))$
  static_files: \1
  upload: .*\.(png|jpg)$

- url: /js
  static_dir: js

- url: /css
  static_dir: css

- url: /fonts
  static_dir: fonts

- url: /stock-api\.php.*
  script: stock-api.php